local M = {}

local function set_highlights(c)
    local hl = vim.api.nvim_set_hl
    local function link(from, to) hl(0, from, { link = to }) end

    hl(0, "Normal", { fg = c.fg0, bg = c.bg0 })
    hl(0, "NormalFloat", { fg = c.fg0, bg = c.bg0 })
    hl(0, "FloatBorder", { fg = c.quartz0, bg = c.bg0 })
    hl(0, "Title", { fg = c.quartz1, bold = true })
    hl(0, "Cursor", { fg = c.bg0, bg = c.yellow })
    hl(0, "Visual", { bg = c.bg2 })
    hl(0, "MatchParen", { fg = c.wisteria, bg = c.bg2, bold = true })
    hl(0, "CursorLine", { bg = "NONE" })
    hl(0, "CursorColumn", { bg = c.bg1 })
    hl(0, "VertSplit", { fg = c.bg2 })
    hl(0, "WinSeparator", { fg = c.bg2 })
    hl(0, "StatusLine", { fg = c.fg0, bg = c.bg05 })
    hl(0, "StatusLineNC", { fg = c.niagara1, bg = c.bg0 })
    hl(0, "SignColumn", { bg = c.bg0 })
    hl(0, "LineNr", { fg = c.bg4, bg = c.bg0 })
    hl(0, "CursorLineNr", { fg = c.yellow, bg = c.bg0 })
    hl(0, "Pmenu", { fg = c.fg0, bg = c.bg05 })
    hl(0, "PmenuSel", { bg = c.bg1 })
    hl(0, "PmenuThumb", { bg = c.bg1 })
    hl(0, "WildMenu", { fg = c.fg0, bg = c.bg2 })
    hl(0, "Search", { fg = c.fg0, bg = c.quartz0 })
    hl(0, "IncSearch", { fg = c.bg0, bg = c.fg0 })
    hl(0, "CurSearch", { fg = c.bg0, bg = c.fg0 })
    hl(0, "Question", { fg = c.green })
    hl(0, "MoreMsg", { fg = c.green })
    hl(0, "ErrorMsg", { fg = c.red })
    hl(0, "WarningMsg", { fg = c.yellow })
    hl(0, "ModeMsg", { fg = c.fg0 })
    hl(0, "SpecialKey", { fg = c.quartz1 })
    hl(0, "Directory", { fg = c.niagara2 })
    hl(0, "NonText", { fg = c.bg4 })
    hl(0, "Whitespace", { fg = c.bg1 })
    hl(0, "EndOfBuffer", { fg = c.bg0 })
    hl(0, "TrailingSpace", { fg = c.red })
    hl(0, "Comment", { fg = c.brown })
    hl(0, "Constant", { fg = c.quartz1 })
    hl(0, "String", { fg = c.green })
    hl(0, "Character", { fg = c.green })
    hl(0, "Number", { fg = c.fg0 })
    hl(0, "Boolean", { fg = c.quartz1 })
    hl(0, "Float", { fg = c.fg0 })
    hl(0, "Identifier", { fg = c.fg0 })
    hl(0, "Function", { fg = c.niagara2 })
    hl(0, "Statement", { fg = c.yellow })
    hl(0, "Conditional", { fg = c.yellow })
    hl(0, "Repeat", { fg = c.yellow })
    hl(0, "Label", { fg = c.yellow })
    hl(0, "Operator", { fg = c.fg0 })
    hl(0, "Keyword", { fg = c.yellow })
    hl(0, "Exception", { fg = c.yellow })
    hl(0, "PreProc", { fg = c.quartz1 })
    hl(0, "Include", { fg = c.quartz1 })
    hl(0, "Define", { fg = c.quartz1 })
    hl(0, "Macro", { fg = c.quartz1 })
    hl(0, "Type", { fg = c.quartz1 })
    hl(0, "StorageClass", { fg = c.yellow })
    hl(0, "Structure", { fg = c.yellow })
    hl(0, "Typedef", { fg = c.yellow })
    hl(0, "Special", { fg = c.quartz1 })
    hl(0, "SpecialComment", { fg = c.brown })
    hl(0, "Underlined", { underline = true })
    hl(0, "Bold", { bold = true })
    hl(0, "Italic", { italic = true })
    hl(0, "Todo", { fg = c.red })
    hl(0, "DiagnosticError", { fg = c.red })
    hl(0, "DiagnosticWarn", { fg = c.yellow })
    hl(0, "DiagnosticInfo", { fg = c.niagara2 })
    hl(0, "DiagnosticHint", { fg = c.green })
    link("DiagnosticSignError", "DiagnosticError")
    link("DiagnosticSignWarn", "DiagnosticWarn")
    link("DiagnosticSignInfo", "DiagnosticInfo")
    link("DiagnosticSignHint", "DiagnosticHint")
    hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.red })
    hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.yellow })
    hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.niagara2 })
    hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.green })
    hl(0, "LspReferenceText", { bg = c.bg2 })
    hl(0, "LspReferenceRead", { bg = c.bg2 })
    hl(0, "LspReferenceWrite", { bg = c.bg2 })
    hl(0, "LspSignatureActiveParameter", { fg = c.yellow, bg = c.bg2 })
    hl(0, "DiffAdd", { fg = c.green, bg = c.bg0 })
    hl(0, "DiffChange", { fg = c.yellow, bg = c.bg0 })
    hl(0, "DiffDelete", { fg = c.red, bg = c.bg0 })
    hl(0, "DiffText", { bg = c.bg_green })
    hl(0, "@variable", { fg = c.fg0 })
    hl(0, "@punctuation", { fg = c.fg0 })
    hl(0, "@module", { fg = c.quartz1 })
    link("@keyword.import.c", "Include")
    link("@keyword.import.cpp", "Include")
    link("@constructor", "Function")
    link("@constructor.cpp", "Function")
    link("@function.method", "Function")
    link("@function.method.call", "Function")
    link("@function.method.call.cpp", "Function")
    hl(0, "markdownH1", { fg = c.quartz1 })
    hl(0, "markdownH2", { fg = c.niagara2 })
    hl(0, "markdownH3", { fg = c.wisteria })
    hl(0, "markdownH4", { fg = c.green })
    hl(0, "markdownH5", { fg = c.quartz1 })
    hl(0, "markdownH6", { fg = c.niagara2 })
    hl(0, "markdownUrl", { fg = c.niagara2 })
    link("markdownCode", "Type")
    hl(0, "TelescopeNormal", { fg = c.fg0, bg = c.bg0 })
    hl(0, "TelescopeBorder", { fg = c.bg2, bg = c.bg0 })
    hl(0, "TelescopeSelection", { bg = c.bg1 })
    hl(0, "TelescopeMatching", { fg = c.green })
    hl(0, "CmpItemAbbr", { fg = c.fg0, bg = c.bg0 })
    hl(0, "CmpItemAbbrMatch", { fg = c.green })
    hl(0, "CmpItemMenu", { fg = c.niagara2 })
    hl(0, "CmpItemAbbrDeprecated", { fg = c.fg0, strikethrough = true })
    hl(0, "CmpBorder", { fg = c.bg2, bg = c.bg1 })
    hl(0, "qfLineNr", { fg = c.quartz1 })
    hl(0, "qfError", { fg = c.red })
end

function M.apply(palette)
    vim.o.background = "dark"
    set_highlights(palette)
end

return M
